version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: polabo_mysql
    hostname: polabo_mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_USER=polabo
      - MYSQL_PASSWORD=polabo
      - MYSQL_ROOT_PASSWORD=polabo
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=polabo
    ports:
      - "3306:3306"


#  redis:
#    image: redis
#    container_name: polabo_redis
#    hostname: polabo_redis
#    ports:
#      - "6379:6379"