spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(pz7EEQu20leZT3uKvGuyvt7YhmLSOJ03yp09o3HSmvk8QqSORYES8Y0iqtjYt3An0uSXVGvd+PdNxXF4h1KXbLm6aMSl2K9gWh2XR5GbIpPAKasqkuha20MGAVckb9NRQC3s0IowzCMvt+jOv0Z1RrAnsfzJy08ZbWe41Slcz/VaQU1hSF6HVohMUrBPApDELlW558sM0jWPfi7NPYNGSlyB4f3bYa0WqjOIAAKPVb3ptvrQwmN7Wg==)
    username: ENC(6B0VWBlhLIFr2ynq8c8jug==)
    password: ENC(klG0liQdqtFK3VDxA89xC1ZIYYzUIz08)
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
#  jpa:
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  jooq:
    sql-dialect: mysql

cloud:
  aws:
    credentials:
      access-key: ENC(PkcItbhMBDzk8j3pjYqRITA5f560l3HOe5rJDCuhxxA=)
      secret-key: ENC(f7qtLdA9YxsjCmV7lNEBnNJlWFeZHl9ztH8Mbe8dgK0N8LJSo8VfrKqlNZKR58fP+fXcxrOJP10=)
    s3:
      bucket: ENC(nLu55KOteQJS+LGFKjfITxZdfaWyZV6C)
    region:
      static: ap-northeast-2

running:
  name: dev

logging:
  discord:
    webhook-uri: ENC(yfeX3WHXQdxkVtasNl5WLv6M/YlN+dVFUurjxGIddstjjipt+KryWKvLu1wDmdGjpuEhUHyaABg4gFWRMk9gNlxSQEE/G1twbuvkOvT0pyFWycVVJ6ryU/v9pDBOS1PSKJY7L3NP66gOGnam6nOvf0Y+F45zZvXj8/sdtR6N798U6fGjFDxOLQ==)