spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/polabo?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: polabo
    password: polabo
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
#  jpa:
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  jooq:
    sql-dialect: mysql



cloud:
  aws:
    credentials:
      access-key: ENC(PkcItbhMBDzk8j3pjYqRITA5f560l3HOe5rJDCuhxxA=)
      secret-key: ENC(f7qtLdA9YxsjCmV7lNEBnNJlWFeZHl9ztH8Mbe8dgK0N8LJSo8VfrKqlNZKR58fP+fXcxrOJP10=)
    s3:
      bucket: ENC(nLu55KOteQJS+LGFKjfITxZdfaWyZV6C)
    region:
      static: ap-northeast-2
aws:
  cloudfront:
    domain: ENC(5AUXhCDMkJlNZa6tI8NIRY3z1kXAtgF0Bb6N3DyujlkOg0iJqK6mV7YYd5rMm1X3)

running:
  name: local

jwt:
  access-key: ENC(43L/PYzgJ86ciTJurdPNLgq49TUMtOgF6ke+Z7d4/wEN2WMu2iakpdDlD2C8d9GUNZzFl0Y9ftK4tk545L5TSv05I5OgbYkBGf2m5O51cjUZmSRg897e+5o+Z5aLgwb1+9tcOcawZR/X9lgkA5hTxlzGc7DHf1vMepLDnbaQBk0I56ieDV314JEEqIaeID72)
  validity:
    access-seconds: 86400000

logging:
  discord:
    webhook-uri: ENC(yfeX3WHXQdxkVtasNl5WLv6M/YlN+dVFUurjxGIddstjjipt+KryWKvLu1wDmdGjpuEhUHyaABg4gFWRMk9gNlxSQEE/G1twbuvkOvT0pyFWycVVJ6ryU/v9pDBOS1PSKJY7L3NP66gOGnam6nOvf0Y+F45zZvXj8/sdtR6N798U6fGjFDxOLQ==)
  level:
    root: INFO